#!/bin/bash
# ARK95X CODE AUDIT MASTER AGENT - RUN AUDIT
# The Emerald Tablet: Full-spectrum code analysis engine
set -uo pipefail

GREEN='\033[1;32m'; BLUE='\033[1;34m'; YELLOW='\033[1;33m'; RED='\033[1;31m'; CYAN='\033[1;36m'; NC='\033[0m'

AUDIT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET="${1:-.}"
REPORT_DIR="$AUDIT_DIR/reports/$(date +%Y%m%d_%H%M%S)"
SUMMARY="$REPORT_DIR/SUMMARY.md"

mkdir -p "$REPORT_DIR"
export PATH="$AUDIT_DIR/.tools:$PATH"

echo -e "${CYAN}============================================${NC}"
echo -e "${CYAN}  EMERALD TABLET - CODE AUDIT MASTER v1.0  ${NC}"
echo -e "${CYAN}============================================${NC}"
echo -e "${BLUE}Target:${NC} $TARGET"
echo -e "${BLUE}Report:${NC} $REPORT_DIR"
echo -e "${BLUE}Time:${NC}   $(date)"
echo ""

TOTAL_ISSUES=0
CRITICAL=0
WARNING=0

cat > "$SUMMARY" << EOF
# Emerald Tablet Audit Report
**Target:** $TARGET
**Date:** $(date)
**Agent:** ARK95X Code Audit Master v1.0

---
EOF

run_layer() {
  local name="$1" cmd="$2" outfile="$3"
  echo -e "${BLUE}[$name]${NC} Running..."
  if eval "$cmd" > "$REPORT_DIR/$outfile" 2>&1; then
    local count=$(wc -l < "$REPORT_DIR/$outfile")
    echo -e "${GREEN}  [$name] Complete - $count lines${NC}"
    echo "## $name" >> "$SUMMARY"
    echo "- Lines: $count" >> "$SUMMARY"
    echo '```' >> "$SUMMARY"
    head -50 "$REPORT_DIR/$outfile" >> "$SUMMARY"
    echo '```' >> "$SUMMARY"
    echo "" >> "$SUMMARY"
    TOTAL_ISSUES=$((TOTAL_ISSUES + count))
  else
    echo -e "${YELLOW}  [$name] Completed with findings${NC}"
    local count=$(wc -l < "$REPORT_DIR/$outfile" 2>/dev/null || echo 0)
    echo "## $name" >> "$SUMMARY"
    echo "- Lines: $count (has findings)" >> "$SUMMARY"
    echo '```' >> "$SUMMARY"
    head -50 "$REPORT_DIR/$outfile" >> "$SUMMARY"
    echo '```' >> "$SUMMARY"
    echo "" >> "$SUMMARY"
    TOTAL_ISSUES=$((TOTAL_ISSUES + count))
  fi
}

echo -e "\n${CYAN}=== LAYER 1: STATIC ANALYSIS ===${NC}"
run_layer "PYLINT" "pylint --recursive=y --output-format=text --score=no '$TARGET' 2>/dev/null || true" "pylint.txt"
run_layer "FLAKE8" "flake8 '$TARGET' 2>/dev/null || true" "flake8.txt"
run_layer "ESLINT" "npx eslint '$TARGET' --format unix 2>/dev/null || true" "eslint.txt"
run_layer "SHELLCHECK" "find '$TARGET' -name '*.sh' -exec shellcheck -f gcc {} + 2>/dev/null || true" "shellcheck.txt"
run_layer "YAMLLINT" "yamllint '$TARGET' 2>/dev/null || true" "yamllint.txt"

echo -e "\n${CYAN}=== LAYER 2: SECURITY ANALYSIS ===${NC}"
run_layer "BANDIT" "bandit -r '$TARGET' -f txt 2>/dev/null || true" "bandit.txt"
run_layer "SEMGREP" "semgrep scan --config auto '$TARGET' --text 2>/dev/null || true" "semgrep.txt"
run_layer "GITLEAKS" "gitleaks detect --source '$TARGET' --report-format json --report-path '$REPORT_DIR/gitleaks.json' 2>/dev/null; cat '$REPORT_DIR/gitleaks.json' 2>/dev/null || true" "gitleaks.txt"

echo -e "\n${CYAN}=== LAYER 3: VULNERABILITY SCAN ===${NC}"
run_layer "TRIVY-FS" "trivy fs '$TARGET' --severity HIGH,CRITICAL 2>/dev/null || true" "trivy-fs.txt"
run_layer "TRIVY-CONFIG" "trivy config '$TARGET' 2>/dev/null || true" "trivy-config.txt"

echo -e "\n${CYAN}=== LAYER 4: TYPE CHECKING ===${NC}"
run_layer "MYPY" "mypy '$TARGET' --ignore-missing-imports 2>/dev/null || true" "mypy.txt"

echo -e "\n${CYAN}=== LAYER 5: CODE METRICS ===${NC}"
echo "### File Statistics" >> "$SUMMARY"
echo '```' >> "$SUMMARY"
find "$TARGET" -type f \( -name '*.py' -o -name '*.ts' -o -name '*.js' -o -name '*.sh' -o -name '*.yml' -o -name '*.yaml' \) | head -200 | while read f; do
  lines=$(wc -l < "$f" 2>/dev/null || echo 0)
  echo "  $lines  $f"
done | sort -rn | head -30 | tee -a "$SUMMARY"
echo '```' >> "$SUMMARY"

# Final summary
echo -e "\n${CYAN}============================================${NC}"
echo -e "${CYAN}  AUDIT COMPLETE - EMERALD TABLET REPORT   ${NC}"
echo -e "${CYAN}============================================${NC}"
echo -e "${BLUE}Total findings:${NC} $TOTAL_ISSUES"
echo -e "${BLUE}Report saved:${NC}   $REPORT_DIR"
echo -e "${BLUE}Summary:${NC}        $SUMMARY"

echo "" >> "$SUMMARY"
echo "---" >> "$SUMMARY"
echo "**Total Findings:** $TOTAL_ISSUES" >> "$SUMMARY"
echo "**Generated by:** ARK95X Emerald Tablet Audit Agent" >> "$SUMMARY"
